# -*- coding: utf-8 -*-
"""
Generate the markdown-based project index for guneysus.github.io-projects.

Produces:
  README.md                     - main navigation / index
  projects/<name>.md            - one page per project
  projects.json                 - machine-readable project data

Usage:
  python scripts/generate.py
"""
import json
import os
import re
import unicodedata

from projects_data import (
    ARCHIVES,
    GITLAB_ARCHIVE_PROJECTS,
    GITHUB_ARCHIVE_PROJECTS,
    GITHUB_ARCHIVE_EXTRA_PROJECTS,
)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECTS_DIR = os.path.join(ROOT, "projects")
DATA_FILE = os.path.join(ROOT, "projects.json")


def slugify(name):
    """Create a filesystem-safe slug from a project name."""
    name = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode("ascii")
    name = re.sub(r"[^a-zA-Z0-9._-]", "-", name)
    return name.strip("-")


def original_url(project):
    """Build a link to the original repository."""
    owner = project["owner"]
    name = project["name"]
    if project["source"] == "github":
        return f"https://github.com/{owner}/{name}"
    return f"https://gitlab.com/{owner}/{name}"


def archive_label(project):
    return ARCHIVES[project["archive_repo"]]["label"]


def archive_url(project):
    """Build a clickable link to the project's current location in the archive monorepo."""
    arch = ARCHIVES[project["archive_repo"]]
    return f"{arch['web_url']}/tree/{arch['branch']}/{project['archive_path']}"


def build_project_page(project, duplicates):
    """Render a single project markdown page."""
    name = project["name"]
    desc = project.get("description") or "*No description available.*"
    vis = "🔓 Public" if project["visibility"] == "public" else "🔒 Private"
    fork = "Yes" if project.get("fork") else "No"
    archived = "✅ Archived" if project.get("archived") else "❌ Not archived"
    dup = "⚠️ **Duplicate** — this project exists in multiple archive monorepos." if name in duplicates else ""

    lines = [
        f"# {name}",
        "",
        f"> {desc}",
        "",
        dup,
        "",
        "## Overview",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| **Name** | `{name}` |",
        f"| **Description** | {desc} |",
        f"| **Visibility** | {vis} |",
        f"| **Fork** | {fork} |",
        f"| **Last activity** | {project.get('last_activity', '—')} |",
        f"| **Status** | {archived} |",
        f"| **Original source** | {project['source'].capitalize()} |",
        f"| **Original owner** | `{project['owner']}` |",
        "",
        "## Links",
        "",
        f"- **Original repository:** [{original_url(project)}]({original_url(project)})",
        f"- **Current location:** [{archive_url(project)}]({archive_url(project)})",
        f"- **Archive monorepo:** {archive_label(project)}",
        f"- **Archive path:** `{project['archive_path']}`",
        "",
        "## Archive Origins",
        "",
    ]
    for origin in ARCHIVES[project["archive_repo"]]["origins"]:
        lines.append(f"- `{origin}`")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"*Generated by `scripts/generate.py` · [Back to index](../README.md)*")
    return "\n".join(lines)


def build_readme(projects, duplicates):
    """Render the main README index."""
    by_source = {"github": [], "gitlab": []}
    for p in projects:
        by_source[p["source"]].append(p)

    # Separate forks from original projects
    originals = [p for p in projects if not p.get("fork")]
    forks = [p for p in projects if p.get("fork")]

    lines = [
        "# 🗂️ Project Archive Index",
        "",
        "> **Metadata & navigation index** for my archived projects, consolidated from multiple "
        "GitHub and GitLab monorepo archives. This repository does **not** contain source code — "
        "it links to the original repositories and the archive monorepos that preserve them.",
        "",
        "## 📦 Archive Monorepos",
        "",
        "| Archive | Local path | Origins |",
        "| --- | --- | --- |",
    ]
    for key, arch in ARCHIVES.items():
        origins = "<br>".join(f"`{o}`" for o in arch["origins"])
        lines.append(f"| **{arch['label']}** | `{arch['local_path']}` | {origins} |")

    lines += [
        "",
        "## 📊 Summary",
        "",
        f"- **Total projects:** {len(projects)}",
        f"- **GitHub projects:** {len(by_source['github'])}",
        f"- **GitLab projects:** {len(by_source['gitlab'])}",
        f"- **Forks:** {len(forks)}",
        f"- **Duplicates (in multiple archives):** {len(duplicates)}",
        "",
        "## ⚠️ Duplicates",
        "",
        "Some projects exist in **more than one** archive monorepo. They may have different "
        "origins and possibly divergent commit histories, so each copy is kept as its own entry.",
        "",
    ]
    if duplicates:
        lines.append("| Project | Archives |")
        lines.append("| --- | --- |")
        for name in sorted(duplicates):
            archs = ", ".join(ARCHIVES[a]["label"] for a in duplicates[name])
            lines.append(f"| `{name}` | {archs} |")
    else:
        lines.append("_No duplicates detected._")
    lines.append("")

    # Combined table for original projects only (forks excluded)
    lines += [
        "## 🗂️ Projects",
        "",
        "| # | Project | Source | Visibility | Archived | Last activity | Description |",
        "| :-: | --- | :-: | :-: | :-: | :-: | --- |",
    ]
    for i, p in enumerate(sorted(originals, key=lambda x: x["name"].lower()), start=1):
        dup = " ⚠️" if p["name"] in duplicates else ""
        src = "🐙 GitHub" if p["source"] == "github" else "🦊 GitLab"
        lines.append(
            f"| {i} | [{p['name']}](projects/{slugify(p['name'])}.md){dup} | "
            f"{src} | "
            f"{'🔓' if p['visibility']=='public' else '🔒'} | "
            f"{'✅' if p.get('archived') else '❌'} | "
            f"{p.get('last_activity','—')} | {p.get('description') or ''} |"
        )
    lines.append("")

    # Forks section
    lines += [
        "## 🍴 Forks",
        "",
        "> Forked repositories — kept for reference, not original projects.",
        "",
        "| # | Project | Source | Visibility | Archived | Last activity | Description |",
        "| :-: | --- | :-: | :-: | :-: | :-: | --- |",
    ]
    for i, p in enumerate(sorted(forks, key=lambda x: x["name"].lower()), start=1):
        dup = " ⚠️" if p["name"] in duplicates else ""
        src = "🐙 GitHub" if p["source"] == "github" else "🦊 GitLab"
        lines.append(
            f"| {i} | [{p['name']}](projects/{slugify(p['name'])}.md){dup} | "
            f"{src} | "
            f"{'🔓' if p['visibility']=='public' else '🔒'} | "
            f"{'✅' if p.get('archived') else '❌'} | "
            f"{p.get('last_activity','—')} | {p.get('description') or ''} |"
        )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Generated by `scripts/generate.py` · Data in `scripts/projects_data.py`*")
    return "\n".join(lines)


def main():
    os.makedirs(PROJECTS_DIR, exist_ok=True)

    # Tag each project with its archive repo
    projects = []
    for p in GITLAB_ARCHIVE_PROJECTS:
        p = dict(p)
        p["archive_repo"] = "gitlab-archive"
        projects.append(p)
    for p in GITHUB_ARCHIVE_PROJECTS:
        p = dict(p)
        p["archive_repo"] = "github-guneysus-archive"
        p["archive_path"] = f"repos/github.com/guneysus-archieve/{p['name']}"
        projects.append(p)
    for p in GITHUB_ARCHIVE_EXTRA_PROJECTS:
        p = dict(p)
        p["archive_repo"] = "github-guneysus-archive"
        p["archive_path"] = f"repos/github.com/guneysus-archieve/{p['name']}"
        projects.append(p)

    # Detect duplicates by name across archives
    by_name = {}
    for p in projects:
        by_name.setdefault(p["name"], []).append(p["archive_repo"])
    duplicates = {name: sorted(set(archs)) for name, archs in by_name.items() if len(set(archs)) > 1}

    # Write per-project pages
    for p in projects:
        page = build_project_page(p, duplicates)
        path = os.path.join(PROJECTS_DIR, f"{slugify(p['name'])}.md")
        with open(path, "w", encoding="utf-8") as f:
            f.write(page)

    # Write README
    readme = build_readme(projects, duplicates)
    with open(os.path.join(ROOT, "README.md"), "w", encoding="utf-8") as f:
        f.write(readme)

    # Write JSON data
    data = {
        "archives": ARCHIVES,
        "duplicates": duplicates,
        "projects": projects,
    }
    with open(DATA_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"Generated {len(projects)} project pages, README.md, and projects.json")
    print(f"Duplicates detected: {len(duplicates)}")


if __name__ == "__main__":
    main()