# -*- coding: utf-8 -*-
"""
Project metadata for the guneysus.github.io-projects index.

Each entry:
  name          : repository/project name (folder name in the archive)
  description   : short description (from GitHub/GitLab metadata)
  visibility    : public | private
  fork          : True if it is a fork
  last_activity : last activity date (YYYY-MM-DD)
  archived      : True if archived in the monorepo
  source        : "github" | "gitlab"  (original hosting platform)
  owner         : original owner/namespace
  original_url  : link to the original repository
  archive_path  : path inside the archive monorepo (relative to archive root)
  archive_repo  : which archive monorepo holds it
"""

# ---------------------------------------------------------------------------
# Archive monorepos (origins)
# ---------------------------------------------------------------------------
ARCHIVES = {
    "gitlab-archive": {
        "label": "GitLab Archive",
        "local_path": r"X:\git\gitlab.com\guneysu\gitlab-archive",
        "web_url": "https://github.com/guneysus/archive",
        "branch": "main",
        "origins": [
            "git@github.com:guneysus/archive.git",
            "git@gitlab.com:guneysu/gitlab-archive.git",
        ],
    },
    "github-guneysus-archive": {
        "label": "GitHub Archive",
        "local_path": r"X:\git\gitlab.com\guneysu\github-guneysus-archive",
        "web_url": "https://gitlab.com/guneysu/github-guneysus-archive",
        "branch": "main",
        "origins": [
            "git@gitlab.com:guneysu/github-guneysus-archive.git",
            "gitea@192.168.1.19:guneysu.dev/github-guneysus-archive.git",
        ],
    },
}

# ---------------------------------------------------------------------------
# Categories for organizing the projects/ folder
# ---------------------------------------------------------------------------
CATEGORIES = {
    "dotnet": {
        "label": ".NET / C#",
        "emoji": "☕",
        "description": "C#, .NET Core, and .NET ecosystem projects",
    },
    "web": {
        "label": "Web",
        "emoji": "🌐",
        "description": "Web apps, sites, themes, and frontend projects",
    },
    "devops": {
        "label": "DevOps & Infra",
        "emoji": "⚙️",
        "description": "CI/CD, containers, homelab, and infrastructure",
    },
    "security": {
        "label": "Security",
        "emoji": "🔐",
        "description": "Security tooling, analysis, and CTF projects",
    },
    "data": {
        "label": "Data & Databases",
        "emoji": "🗄️",
        "description": "Databases, SQL, and data tooling",
    },
    "cli": {
        "label": "CLI Tools",
        "emoji": "💻",
        "description": "Command-line tools and utilities",
    },
    "learning": {
        "label": "Learning & Notes",
        "emoji": "📚",
        "description": "Tutorials, courses, and knowledge bases",
    },
    "personal": {
        "label": "Personal & Sites",
        "emoji": "👤",
        "description": "Personal sites, blogs, and CV",
    },
    "misc": {
        "label": "Miscellaneous",
        "emoji": "📦",
        "description": "Projects that don't fit a specific category",
    },
}

# Project name -> category key. Projects not listed here default to "misc".
PROJECT_CATEGORIES = {
    # --- .NET / C# ---
    ".cli-template_dotnet": "dotnet",
    "acme-welcome-dotnet": "dotnet",
    "analyzers": "dotnet",
    "asp-net-sample-apps": "dotnet",
    "aspcore-sample-apps": "dotnet",
    "aspnet-core-streaming": "dotnet",
    "crem": "dotnet",
    "csharp-connected-disconnected": "dotnet",
    "csharp.dotnet.custom-config-generator": "dotnet",
    "csharp.generic.db.view": "dotnet",
    "csharp.hw.northwind.sepet": "dotnet",
    "csharp.mvc.blog.hw": "dotnet",
    "csharp.mvc.nw.intro": "dotnet",
    "csharp.oop.uygulama": "dotnet",
    "csharp.winforms.autocomplete": "dotnet",
    "dingil": "dotnet",
    "dinq": "dotnet",
    "dotnet-core-plugins": "dotnet",
    "dotnet-dynamic-assembly-loading": "dotnet",
    "dotnet-expression-trees": "dotnet",
    "dotnet-extension-methods": "dotnet",
    "dotnet-how-to-debug-source-generator-vs2022": "dotnet",
    "dotnet-html-gen": "dotnet",
    "dotnet-mock-server": "dotnet",
    "dotnet-reversing": "dotnet",
    "dotnet-sandbox": "dotnet",
    "dotnet-sandbox-2": "dotnet",
    "dotnetcore-imageserver": "dotnet",
    "DotNetHooking": "dotnet",
    "EfCoreQueryToolbar": "dotnet",
    "extension-methods": "dotnet",
    "fullstack-dotnet-template": "dotnet",
    "GraphQL.Tools": "dotnet",
    "hg": "dotnet",
    "interview-downtime-alerter-service": "dotnet",
    "interview-project-mars-rover-tdd": "dotnet",
    "NanoDbProfiler": "dotnet",
    "NullCollectionFix.Fody": "dotnet",
    "NullFixEnumerable.Fody": "dotnet",
    "peview": "dotnet",
    "prank.var.sourcegenerator": "dotnet",
    "predicate-builder": "dotnet",
    "sandbox-net": "dotnet",
    "sid": "dotnet",
    "speedcrunch.net": "dotnet",
    "sql-query-profiler": "dotnet",
    "sql-query-profiler-sample-apps": "dotnet",
    "testere": "dotnet",
    "todo-gql": "dotnet",
    "Typr": "dotnet",
    "Typr.Source": "dotnet",
    "underscore-net-docs": "dotnet",
    "underscore.net": "dotnet",
    "wxdatcom": "dotnet",
    "wxdatcom-2": "dotnet",
    # --- Web ---
    "app.namazvaktim": "web",
    "blog-from-scratch": "web",
    "blog-v1": "web",
    "blog-v2": "web",
    "blog-v3": "web",
    "blog-v3-theme": "web",
    "browser-pick": "web",
    "calcx": "web",
    "chess.js": "web",
    "form-flow": "web",
    "galeri.nakizeyn.guneysu.dev": "web",
    "gohugo-hacker": "web",
    "guneysu.dev": "web",
    "guneysus.github.io-archieved": "web",
    "hugo-theme-monochrome": "web",
    "openresty-twitter-clone": "web",
    "personal-blog-theme-gohugo-soothing": "web",
    "pw": "web",
    "snow-flakes-js": "web",
    "tutorial-serverless-contact-form": "web",
    "web-layouts": "web",
    "whatismybrowser": "web",
    # --- DevOps & Infra ---
    "backstage": "devops",
    "bug.report-docker-3106": "devops",
    "cloudflare-worker-get-user": "devops",
    "configs": "devops",
    "deployement-templates": "devops",
    "Devup": "devops",
    "docker-apps": "devops",
    "docker-images": "devops",
    "dotfiles": "devops",
    "gitops-config": "devops",
    "homelab-caddy-config": "devops",
    "openresty-gateway-waf": "devops",
    "proxmox-scripts": "devops",
    "skaf": "devops",
    "templates": "devops",
    # --- Security ---
    "git-ctf": "security",
    "lcnc-security-engine": "security",
    "sql-injection": "security",
    "vulnerable-api": "security",
    "wsdl2swagger2openapi": "security",
    # --- Data & Databases ---
    "mssql-tools": "data",
    "python-sqlite-json-explorer": "data",
    "sitemap-parser": "data",
    "SqlServer.Rules": "data",
    "torque-collector": "data",
    "torque-collector-net-clickhouse": "data",
    # --- CLI Tools ---
    "git-jump": "cli",
    "grepz": "cli",
    "ndig": "cli",
    "nqrgen": "cli",
    "pake": "cli",
    "rende": "cli",
    # --- Learning & Notes ---
    "algoritms": "learning",
    "grammars": "learning",
    "kb": "learning",
    "Language-Designs-For-Web": "learning",
    "latex-docs": "learning",
    "learn-agentic-ai": "learning",
    "learn-fsharp": "learning",
    "learn-go": "learning",
    "learn-lisp": "learning",
    "learn-mastering-dotnet-expression-trees": "learning",
    "learn-mcp": "learning",
    "learn-prometheus": "learning",
    "learning": "learning",
    "llm": "learning",
    "memoryleak": "learning",
    "mevlana-takvimi": "learning",
    "prompt-library": "learning",
    "prompts": "learning",
    "ramblings": "learning",
    "sd-llm-benchmark": "learning",
    "Startup-CTO-Handbook": "learning",
    "swe-route-optimization-project": "learning",
    # --- Personal & Sites ---
    "cv": "personal",
    "guneysus": "personal",
    "keychron-layouts": "personal",
    "musahid": "personal",
    "surmene": "personal",
    # --- Misc (explicit) ---
    "ai": "misc",
    "bginfz": "misc",
    "boilerplate": "misc",
    "calcpaper": "misc",
    "firebase-studio-apex-cloud-sample": "misc",
    "git-presentation": "misc",
    "goreplay": "misc",
    "humanizer-tr": "misc",
    "kvb-iot-demo": "misc",
    "parsers": "misc",
    "project-incubation": "misc",
    "pytotube": "misc",
    "sensorfusion-gps-process": "misc",
    "side-projects": "misc",
    "unicode_tr": "misc",
    "wox-prayer-times-plugin": "misc",
}

# ---------------------------------------------------------------------------
# Projects from gitlab-archive  (repos/guneysu + repos/guneysu.dev)
# ---------------------------------------------------------------------------
GITLAB_ARCHIVE_PROJECTS = [
    # --- guneysu namespace ---
    dict(name="backstage", description="", visibility="private", fork=False,
         last_activity="2026-08-02", archived=True, source="gitlab",
         owner="guneysu", archive_path="repos/guneysu/backstage"),
    dict(name="docker-apps", description="", visibility="private", fork=False,
         last_activity="2026-08-02", archived=True, source="gitlab",
         owner="guneysu", archive_path="repos/guneysu/docker-apps"),
    dict(name="dotnet-extension-methods", description="", visibility="private", fork=False,
         last_activity="2026-08-02", archived=True, source="gitlab",
         owner="guneysu", archive_path="repos/guneysu/dotnet-extension-methods"),
    dict(name="fullstack-dotnet-template", description="", visibility="private", fork=False,
         last_activity="2026-08-02", archived=True, source="gitlab",
         owner="guneysu", archive_path="repos/guneysu/fullstack-dotnet-template"),
    dict(name="gitops-config", description="k8s manifests files for continious deployment",
         visibility="private", fork=False, last_activity="2026-08-02", archived=True,
         source="gitlab", owner="guneysu", archive_path="repos/guneysu/gitops-config"),
    dict(name="homelab-caddy-config", description="", visibility="private", fork=False,
         last_activity="2026-08-02", archived=True, source="gitlab",
         owner="guneysu", archive_path="repos/guneysu/homelab-caddy-config"),
    dict(name="latex-docs", description="", visibility="private", fork=False,
         last_activity="2026-08-02", archived=True, source="gitlab",
         owner="guneysu", archive_path="repos/guneysu/latex-docs"),
    dict(name="parsers", description="", visibility="private", fork=False,
         last_activity="2026-08-02", archived=True, source="gitlab",
         owner="guneysu", archive_path="repos/guneysu/parsers"),
    dict(name="project-incubation", description="", visibility="private", fork=False,
         last_activity="2026-08-02", archived=True, source="gitlab",
         owner="guneysu", archive_path="repos/guneysu/project-incubation"),
    dict(name="prompt-library", description="LLM Prompts", visibility="private", fork=False,
         last_activity="2026-08-02", archived=True, source="gitlab",
         owner="guneysu", archive_path="repos/guneysu/prompt-library"),
    dict(name="surmene", description="", visibility="private", fork=False,
         last_activity="2026-08-02", archived=True, source="gitlab",
         owner="guneysu", archive_path="repos/guneysu/surmene"),
    dict(name="templates", description="", visibility="private", fork=False,
         last_activity="2026-08-02", archived=True, source="gitlab",
         owner="guneysu", archive_path="repos/guneysu/templates"),
    dict(name="torque-collector", description="", visibility="private", fork=False,
         last_activity="2026-08-02", archived=True, source="gitlab",
         owner="guneysu", archive_path="repos/guneysu/torque-collector"),
    # --- guneysu.dev namespace ---
    dict(name="acme-welcome-dotnet", description="", visibility="private", fork=False,
         last_activity="2026-08-02", archived=True, source="gitlab",
         owner="guneysu.dev", archive_path="repos/guneysu.dev/acme-welcome-dotnet"),
    dict(name="cloudflare-worker-get-user", description="", visibility="private", fork=False,
         last_activity="2026-08-02", archived=True, source="gitlab",
         owner="guneysu.dev", archive_path="repos/guneysu.dev/cloudflare-worker-get-user"),
    dict(name="form-flow", description="", visibility="private", fork=False,
         last_activity="2026-08-02", archived=True, source="gitlab",
         owner="guneysu.dev", archive_path="repos/guneysu.dev/form-flow"),
    dict(name="skaf", description="", visibility="private", fork=False,
         last_activity="2026-08-02", archived=True, source="gitlab",
         owner="guneysu.dev", archive_path="repos/guneysu.dev/skaf"),
]

# ---------------------------------------------------------------------------
# Projects from github-guneysus-archive  (repos/github.com/guneysus-archieve)
# ---------------------------------------------------------------------------
GITHUB_ARCHIVE_PROJECTS = [
    dict(name=".cli-template_dotnet", description=".NET CLI Tool Template", visibility="private", fork=False, last_activity="2024-12-11", archived=False, source="github", owner="guneysus"),
    dict(name="aes", description="AES-256 block cipher", visibility="public", fork=True, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="aes_dust", description="Unlicensed tiny / small portable implementation of 128/256-bit AES encryption in C, x86, AMD64, ARM32 and ARM64 assembly", visibility="public", fork=True, last_activity="2021-02-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="ai", description="", visibility="public", fork=False, last_activity="2026-06-29", archived=False, source="github", owner="guneysus"),
    dict(name="algoritms", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="analyzers", description="C# code analyzers", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="app.namazvaktim", description="https://guneysus.github.io/app.namazvaktim/", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="asm", description="Learning assembly for linux-x64", visibility="public", fork=True, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="asp-net-sample-apps", description="", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="aspcore-sample-apps", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="aspnet-core-streaming", description="ASP.Net Streaming to the Client", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="aws_list_all", description="List all your AWS resources, all regions, all services.", visibility="public", fork=True, last_activity="2021-02-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="bginfz", description="", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="bin", description="", visibility="public", fork=True, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="blog-from-scratch", description="", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="blog-v1", description="blog sources", visibility="private", fork=False, last_activity="2025-09-06", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="blog-v2", description="", visibility="private", fork=False, last_activity="2025-10-11", archived=False, source="github", owner="guneysus"),
    dict(name="blog-v3", description="", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="blog-v3-theme", description="", visibility="private", fork=False, last_activity="2025-06-05", archived=False, source="github", owner="guneysus"),
    dict(name="boilerplate", description="Boilerplate file templates to be used by copier", visibility="public", fork=False, last_activity="2025-10-03", archived=False, source="github", owner="guneysus"),
    dict(name="browser-pick", description="Android like selecting application for specific URLs, protocols etc. [WIP]", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="bug.report-docker-3106", description="", visibility="public", fork=False, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="calc.asm", description="Minimal arithmetic calculator in x86 assembly", visibility="public", fork=True, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="calcx", description="Calcx", visibility="public", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="chess.js", description="A brand new OOP Chess modeling with ES6", visibility="public", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="coding-interview-university", description="A complete computer science study plan to become a software engineer.", visibility="public", fork=True, last_activity="2021-05-08", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="configs", description="", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="CoreHook", description="A library that simplifies intercepting application function calls using managed code and the .NET Core runtime", visibility="public", fork=True, last_activity="2022-10-13", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="Craig-s-Utility-Library", description="Main repo for Craig's Utility Library", visibility="public", fork=True, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="crem", description="Crud Made Easy for .asp net core", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="CSharpExpressionTreesInTheRealWorld", description="Slides plus links for my talk, C# Expression Trees in the Real World", visibility="public", fork=True, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="cv", description="my cv", visibility="private", fork=False, last_activity="2026-05-17", archived=False, source="github", owner="guneysus"),
    dict(name="de4dot", description=".NET deobfuscator and unpacker.", visibility="public", fork=True, last_activity="2023-04-05", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="deployement-templates", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="Design-Patterns", description="You can find here bunch of useful design patterns to help your project", visibility="public", fork=True, last_activity="2021-02-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="Devup", description="YAML based, docker-compose like tools, helping to start development environments. The idea @ybrs's project-switcher, reimplemented with .NET.", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="dingil", description="Generate POCO class and assembly by only defining an YAML file", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="dinq", description="Dynamic Query Tool", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="dlr", description="Dynamic Language Runtime", visibility="public", fork=True, last_activity="2021-01-03", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="do-not-reinvent", description="My technical memo", visibility="public", fork=True, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="docker-apps", description="", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="docker-baseimage-rdesktop", description="base image for xrdp containers", visibility="public", fork=True, last_activity="2022-02-26", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="docker-baseimage-rdesktop-web", description="Custom all in one container for running GUI apps from a web browser", visibility="public", fork=True, last_activity="2025-01-15", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="docker-images", description="docker images that updated regulary by TravisCI", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="docker-rdesktop", description="", visibility="public", fork=True, last_activity="2022-02-26", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="DoH-IP-blocklists", description="This repo contains the domain names and the IPv4/IPv6 addresses of public DoH server", visibility="public", fork=True, last_activity="2026-08-01", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="dotfiles", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="dotnet-core-plugins", description=".NET core plugging architechture", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="dotnet-dynamic-assembly-loading", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="dotnet-expression-trees", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="dotnet-how-to-debug-source-generator-vs2022", description="Step by step guide on how to debug a C# SourceGenerator in Visual Studio 2022", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="dotnet-html-gen", description="Generate HTML with fluent API", visibility="public", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="dotnet-mock-server", description="declarative mock server with fake data generation capabilities for .NET Core 2.1+", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="dotnet-reversing", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="dotnet-sandbox", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="dotnet-sandbox-2", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="EfCoreQueryToolbar", description="Intercepts SQL queries from Entity Framework Core and shows them in an HTML toolbar within your web app.", visibility="public", fork=False, last_activity="2025-10-18", archived=False, source="github", owner="guneysus"),
    dict(name="extension-methods", description="", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="EzanVaktiAPI", description="Tüm dünya ülkeleri için Diyanet İşleri Başkanlığı'nın yıllık ezan vakitleri.", visibility="public", fork=True, last_activity="2023-01-28", archived=False, source="github", owner="guneysus-archieve"),
    dict(name="firebase-studio-apex-cloud-sample", description="", visibility="private", fork=False, last_activity="2025-09-23", archived=False, source="github", owner="guneysus"),
    dict(name="galeri.nakizeyn.guneysu.dev", description="Migrated Instagram Photos to a GoHugo web site", visibility="private", fork=False, last_activity="2024-11-15", archived=False, source="github", owner="guneysus"),
    dict(name="git-jump", description="quickly jump branches from CLI", visibility="public", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="gohugo-hacker", description="Hacker Theme for Hugo live demo", visibility="public", fork=False, last_activity="2026-07-01", archived=False, source="github", owner="guneysus"),
    dict(name="goreplay", description="GoReplay is an open-source tool for capturing and replaying live HTTP traffic into a test environment in order to continuously test your system with real data. It can be used to increase confidence in code deployments, configuration changes and infrastructure changes.", visibility="private", fork=False, last_activity="2025-10-17", archived=False, source="github", owner="guneysus"),
    dict(name="grammars", description="", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="GraphQL.Tools", description="GraphQL.Tools is a GraphQL to C# compiler (code-generator) which turns your GraphQL schema into a set of C# classes, interfaces, and enums.", visibility="public", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="grepz", description="", visibility="private", fork=False, last_activity="2025-04-02", archived=False, source="github", owner="guneysus"),
    dict(name="guneysu.dev", description="personal landing page", visibility="private", fork=False, last_activity="2025-09-14", archived=False, source="github", owner="guneysus"),
    dict(name="guneysus", description="", visibility="private", fork=False, last_activity="2023-04-05", archived=False, source="github", owner="guneysus"),
    dict(name="guneysus.github.io-archieved", description="github home page", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="hugo-theme-monochrome", description="Monochrome is a fast, clean and responsive hugo theme", visibility="private", fork=False, last_activity="2025-10-17", archived=False, source="github", owner="guneysus"),
    dict(name="kb", description="", visibility="private", fork=False, last_activity="2025-08-17", archived=False, source="github", owner="guneysus"),
    dict(name="keychron-layouts", description="Keychron layouts", visibility="private", fork=False, last_activity="2025-10-08", archived=False, source="github", owner="guneysus"),
    dict(name="keys", description="", visibility="public", fork=True, last_activity="2023-01-28", archived=False, source="github", owner="guneysus-archieve"),
    dict(name="Language-Designs-For-Web", description="", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="lcnc-security-engine", description="Static security analysis engine for low-code / no-code workflows (parsguru, n8n, make etc..). Detects hardcoded secrets, insecure transport, blind trust, and more - with optional LLM-powered semantic review.", visibility="public", fork=True, last_activity="2026-07-06", archived=False, source="github", owner="guneysus"),
    dict(name="learn-agentic-ai", description="", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="learn-fsharp", description="", visibility="private", fork=False, last_activity="2026-07-17", archived=False, source="github", owner="guneysus"),
    dict(name="learn-go", description="", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="learn-lisp", description="", visibility="private", fork=False, last_activity="2026-07-16", archived=False, source="github", owner="guneysus"),
    dict(name="learn-mastering-dotnet-expression-trees", description="", visibility="private", fork=False, last_activity="2026-07-17", archived=False, source="github", owner="guneysus"),
    dict(name="learn-mcp", description="", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="learn-prometheus", description="", visibility="private", fork=False, last_activity="2026-07-30", archived=False, source="github", owner="guneysus"),
    dict(name="learning", description="", visibility="private", fork=False, last_activity="2024-12-06", archived=False, source="github", owner="guneysus"),
    dict(name="llm", description="", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="memoryleak", description="", visibility="private", fork=False, last_activity="2025-04-02", archived=False, source="github", owner="guneysus"),
    dict(name="mevlana-takvimi", description="", visibility="private", fork=False, last_activity="2022-11-20", archived=False, source="github", owner="guneysus"),
    dict(name="NanoDbProfiler", description="A tiny profiler without hassle.", visibility="public", fork=False, last_activity="2026-01-09", archived=False, source="github", owner="guneysus"),
    dict(name="ndig", description="dig like simple CLI DNS Lookup tool, implemented with .NET Core", visibility="public", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="nqrgen", description="CLI based QR generator", visibility="public", fork=False, last_activity="2026-01-09", archived=False, source="github", owner="guneysus"),
    dict(name="NullCollectionFix.Fody", description="Fixes IEnumerables that returns null by returning Empty Array.", visibility="public", fork=False, last_activity="2025-10-18", archived=False, source="github", owner="guneysus"),
    dict(name="NullFixEnumerable.Fody", description="", visibility="private", fork=False, last_activity="2024-11-26", archived=False, source="github", owner="guneysus"),
    dict(name="pake", description="GNU Make like simple build/automation tool implemented with Powershell", visibility="private", fork=False, last_activity="2025-04-02", archived=False, source="github", owner="guneysus"),
    dict(name="parsers", description="Modular Antlr4 Parser & Lexers for big projects", visibility="public", fork=False, last_activity="2026-01-09", archived=False, source="github", owner="guneysus"),
    dict(name="personal-blog-theme-gohugo-soothing", description="Blog Theme", visibility="public", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="PluginFramework", description="Everything is a Plugin in .NET", visibility="public", fork=True, last_activity="2025-10-21", archived=False, source="github", owner="guneysus"),
    dict(name="prank.var.sourcegenerator", description="", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="prompts", description="Prompt Library", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="proxmox-scripts", description="", visibility="public", fork=False, last_activity="2026-07-16", archived=False, source="github", owner="guneysus"),
    dict(name="ramblings", description="", visibility="public", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="rende", description="CLI based template renderer with various engines", visibility="public", fork=False, last_activity="2026-01-09", archived=False, source="github", owner="guneysus"),
    dict(name="sd-llm-benchmark", description="", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="sql-query-profiler", description="", visibility="public", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="sql-query-profiler-sample-apps", description="", visibility="private", fork=False, last_activity="2025-02-07", archived=False, source="github", owner="guneysus"),
    dict(name="SqlServer.Rules", description="120+ SQL Server static code analysis rules for SQL Database Projects", visibility="private", fork=False, last_activity="2025-04-02", archived=False, source="github", owner="guneysus"),
    dict(name="Startup-CTO-Handbook", description="The Startup CTO's Handbook, a book covering leadership, management and technical topics for leaders of software engineering teams", visibility="private", fork=False, last_activity="2025-04-02", archived=False, source="github", owner="guneysus"),
    dict(name="swe-route-optimization-project", description="", visibility="private", fork=False, last_activity="2026-07-18", archived=False, source="github", owner="guneysus"),
    dict(name="todo-gql", description="GraphQL Todo Example", visibility="public", fork=False, last_activity="2026-01-09", archived=False, source="github", owner="guneysus"),
    dict(name="torque-collector-net-clickhouse", description="", visibility="private", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="tutorial-serverless-contact-form", description="Developing a Serverless Contact Form via Netlify Functions and Cloudflare Zero Trust", visibility="private", fork=False, last_activity="2025-10-10", archived=False, source="github", owner="guneysus"),
    dict(name="Typr", description="Typr public repo for documentation and website", visibility="public", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="Typr.Source", description="Typer DSL to create C# Types with ease.", visibility="public", fork=False, last_activity="2026-01-09", archived=False, source="github", owner="guneysus"),
    dict(name="whatismybrowser", description="a simple https://www.whatsmybrowser.org clone but on the client side.", visibility="public", fork=False, last_activity="2024-10-14", archived=False, source="github", owner="guneysus-archieve"),
    dict(name="wsdl2swagger2openapi", description="Converts WSDL files to OpenAPI v3.0.x, streamlining API scan integration with Burp Suite", visibility="private", fork=False, last_activity="2025-10-17", archived=False, source="github", owner="guneysus"),
    dict(name="wxdatcom", description="My Graduate Project /  Interactive DATCOM wxWidgets GUI", visibility="public", fork=False, last_activity="2023-01-28", archived=False, source="github", owner="guneysus-archieve"),
    dict(name="dotnetcore-imageserver", description="aspnet core image resizing web app with upload, delete support via REST interface", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="DotNetHooking", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="DotNextMoscow2019", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="git-ctf", description="Hey! Git gurus, capture the flag from this repository 🐱‍👤 🏴", visibility="public", fork=False, last_activity="2026-05-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="git-presentation", description='This repo (will) contain the presentation "Git & Github Guide"', visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="hg", description="HG: DSL for Html Generation", visibility="public", fork=False, last_activity="2026-07-31", archived=False, source="github", owner="guneysus"),
    dict(name="har-spec", description="The HTTP Archive Spec", visibility="public", fork=True, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="heceleme", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="Heijden.Dns", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="humanizer-tr", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="ildasm", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="ILProgramming", description="Coding close to the .NET Runtime using ILProj, ildasm, ilasm", visibility="public", fork=True, last_activity="2023-02-18", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="ILProj", description="", visibility="public", fork=True, last_activity="2023-01-24", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="interview-downtime-alerter-service", description="Downtime Alert Service with ASP.Net Core", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="interview-project-mars-rover-tdd", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="kvb-iot-demo", description="", visibility="public", fork=False, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="LightQuery", description="Lightweight solution for sorting and paging Asp.Net Core API results", visibility="public", fork=True, last_activity="2021-04-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="loadlibrary", description="Porting Windows Dynamic Link Libraries to Linux", visibility="public", fork=True, last_activity="2021-02-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="managed-x86", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="MethodRedirect", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="minsk", description="This repo contains Minsk, a handwritten compiler in C#. It illustrates basic concepts of compiler construction and how one can tool the language inside of an IDE by exposing APIs for parsing and type checking.", visibility="public", fork=True, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="mssql-TableTruncate", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="mssql-tools", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="mssqlfs", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="musahid", description="", visibility="public", fork=False, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="nemerle", description="Nemerle language. Main repository.", visibility="public", fork=True, last_activity="2022-12-22", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="NGINX-Demos", description="NGINX and NGINX Plus demos", visibility="public", fork=True, last_activity="2021-04-04", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="NRules", description="Rules engine for .NET, based on the Rete matching algorithm, with internal DSL in C#.", visibility="public", fork=True, last_activity="2021-11-03", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="ntpserver", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="Object-Initialization-in-CSharp", description="A C# Pill that highlights the order in which the fields, properties and constructors, both static and instance, are initialized in C#.", visibility="public", fork=True, last_activity="2022-12-19", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="openresty-gateway-waf", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="openresty-twitter-clone", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="Parallel-Evolution", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="perfect-presentation", description="This project contains all steps which you need to make a perfect presentation. You creating a wonderful presentation is our role and our priority.", visibility="public", fork=True, last_activity="2021-02-25", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="performance-optimization", description="Guidance on how to observe, measure, and correct common issues in a cloud-based system.", visibility="public", fork=True, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="peview", description="Web based HEX viewer. The goal was developing a Web based PE Viewer.", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="PiOBDII", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="playbook", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="pose", description="Replace any .NET method (including static and non-virtual) with a delegate", visibility="public", fork=True, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="prayer-times-android", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="prayer-times-api", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="predicate-builder", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="project-switcher", description="hassle free project switching", visibility="public", fork=True, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="pw", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="python-sqlite-json-explorer", description="", visibility="public", fork=False, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="pytotube", description="Simple 1D Thermal problem solver", visibility="public", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="Random-Problems", description="What actually happens when we use a Random instance from multiple threads? Can we do something to make it thread-safe?", visibility="public", fork=True, last_activity="2021-12-16", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="sandbox-net", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="selenium-webdriver-winappdriver-example", description="An example of selenium-webdriver and winappdriver integration", visibility="public", fork=True, last_activity="2022-01-04", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="sensorfusion-gps-process", description="", visibility="public", fork=False, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="sid", description="Simple Declarative Web Apps", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="side-projects", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="sitemap-parser", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="snake", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="snow-flakes-js", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="speedcrunch.net", description="Parser based expression evaluator", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="sql-injection", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="sscli20_20060311", description="Version: 2.0 Date Published: 3/23/2006. The Shared Source CLI is a compressed archive of the source code to a working implementation of the ECMA CLI and the ECMA C# language specification. This implementation builds and runs on Windows XP.", visibility="public", fork=True, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="symreader-converter", description="Converts between Windows PDB and Portable PDB formats.", visibility="public", fork=True, last_activity="2021-02-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="testere", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="Todos", description="Various todo list backend API implementations", visibility="public", fork=True, last_activity="2021-02-26", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="underscore-net-docs", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="underscore.net", description="Simple, Handy Toolkits for .NET Core projects with high test coverage.", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="understanding-csrf", description="What are CSRF tokens and how do they work?", visibility="public", fork=True, last_activity="2023-01-28", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="unicode_tr", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="uxplay", description="", visibility="public", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="Virtual-in-Constructor", description="This pill demonstrates why it is not a good idea to call abstract or virtual methods from the constructor.", visibility="public", fork=True, last_activity="2022-12-19", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="vulnerable-api", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="web-layouts", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="wox-prayer-times-plugin", description="wox prayer times plugin", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="wxdatcom-2", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
]

# Projects present in the archive folder but NOT in the README table (extra)
GITHUB_ARCHIVE_EXTRA = [
    ".template-powershell-core-binary-module", "Antlr4.Extension", "ascii_b64",
    "asprofiled", "bin_b64", "calcpaper", "clr-profiling", "csharp-connected-disconnected",
    "csharp.dotnet.custom-config-generator", "csharp.generic.db.view",
    "csharp.hw.northwind.sepet", "csharp.mvc.blog.hw", "csharp.mvc.nw.intro",
    "csharp.oop.uygulama", "csharp.winforms.autocomplete", "des", "Disposable-Pattern",
    "dot",
]

# Full metadata for the extra projects found in the archive folder
GITHUB_ARCHIVE_EXTRA_PROJECTS = [
    dict(name=".template-powershell-core-binary-module", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="Antlr4.Extension", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="ascii_b64", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="asprofiled", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="bin_b64", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="calcpaper", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="clr-profiling", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="csharp-connected-disconnected", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="csharp.dotnet.custom-config-generator", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="csharp.generic.db.view", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="csharp.hw.northwind.sepet", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="csharp.mvc.blog.hw", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="csharp.mvc.nw.intro", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="csharp.oop.uygulama", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="csharp.winforms.autocomplete", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="des", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="Disposable-Pattern", description="", visibility="private", fork=True, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
    dict(name="dot", description="", visibility="private", fork=False, last_activity="2024-10-14", archived=True, source="github", owner="guneysus-archieve"),
]

# ---------------------------------------------------------------------------
# Duplicates are detected automatically by the generator: any project name
# that appears in more than one archive monorepo is flagged as a duplicate.
# The same project may have multiple origins and possibly different commit
# histories across archives, so each copy is kept as its own entry.
# ---------------------------------------------------------------------------